config/routes.rb
Surveys::Application.routes.draw do
  resources :flashes

  mount Surveyor::Engine => "/surveys", :as => "surveyor"

   root :to => 'flashes#index'

end

app/models/flash.rb
class Flash < ActiveRecord::Base
  attr_accessible :age, :name, :query
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/flashes_controller.rb
class FlashesController < ApplicationController
  # GET /flashes
  # GET /flashes.json
  def index
    @flashes = Flash.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @flashes }
    end
  end

  # GET /flashes/1
  # GET /flashes/1.json
  def show
    @flash = Flash.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @flash }
    end
  end

  # GET /flashes/new
  # GET /flashes/new.json
  def new
    @flash = Flash.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @flash }
    end
  end

  # GET /flashes/1/edit
  def edit
    @flash = Flash.find(params[:id])
  end

  # POST /flashes
  # POST /flashes.json
  def create
    @flash = Flash.new(params[:flash])

    respond_to do |format|
      if @flash.save
        format.html { redirect_to @flash, notice: 'Flash was successfully created.' }
        format.json { render json: @flash, status: :created, location: @flash }
      else
        format.html { render action: "new" }
        format.json { render json: @flash.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /flashes/1
  # PUT /flashes/1.json
  def update
    @flash = Flash.find(params[:id])

    respond_to do |format|
      if @flash.update_attributes(params[:flash])
        format.html { redirect_to @flash, notice: 'Flash was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @flash.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flashes/1
  # DELETE /flashes/1.json
  def destroy
    @flash = Flash.find(params[:id])
    @flash.destroy

    respond_to do |format|
      format.html { redirect_to flashes_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
	def index
	end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/flashes/_form.html.erb
<%= form_for(@flash) do |f| %>
  <% if @flash.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flash.errors.count, "error") %> prohibited this flash from being saved:</h2>

      <ul>
      <% @flash.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br />
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :query %><br />
    <%= f.text_area :query %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flashes/edit.html.erb
<h1>Editing flash</h1>

<%= render 'form' %>

<%= link_to 'Show', @flash %> |
<%= link_to 'Back', flashes_path %>

app/views/flashes/index.html.erb
<h1>Listing flashes</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Query</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @flashes.each do |flash| %>
  <tr>
    <td><%= flash.name %></td>
    <td><%= flash.age %></td>
    <td><%= flash.query %></td>
    <td><%= link_to 'Show', flash %></td>
    <td><%= link_to 'Edit', edit_flash_path(flash) %></td>
    <td><%= link_to 'Destroy', flash, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Flash', new_flash_path %>

app/views/flashes/new.html.erb
<h1>New flash</h1>

<%= render 'form' %>

<%= link_to 'Back', flashes_path %>

app/views/flashes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @flash.name %>
</p>

<p>
  <b>Age:</b>
  <%= @flash.age %>
</p>

<p>
  <b>Query:</b>
  <%= @flash.query %>
</p>


<%= link_to 'Edit', edit_flash_path(@flash) %> |
<%= link_to 'Back', flashes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Surveys</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/surveys/index.html.erb
<h1>Welcome to my surveys<h1>

	<h2>This is a test<h2>